language: node_js

node_js:
  - node

before_script:
  - npm install -g jasmine
  - npm install

script:
  - npm test

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info

addons:
  code_climate:
  repo_token:
    secure: zkyjQzSKWG/xVCvj/1VEGE/Dry3NERzCT7qfB4suM8/qMw9UOFenUWXcJBXCZjAXid9KfCUGR1gPB4SIOYQOvSslbagmIeCgAHsDVJt/te1RzOdgIuEqGCjgx1qymAWW3M/0IRYi6sGvftuKR6MD5baW6xaB3by21enBJN4/0b7JyAj3Uk2fCUStqbTHnCGULKkDSdWzs2A3Ys6XspXj1AQcZxs0tIVyIB1qjc9neNoFrIqrDKyyg2NtedmFztUt7NbCnDy1Yj4IEZZjNgdHJ//sBTqqjtGDLgjljCTcl6g7pKIzoSbsrA2ixDSVncRJNeWJsLGaeFV4uPH+w/xW44xvl6QdRJqgKNwmqZavu+DexL3J55qbybsHIOeTjDPJYt4TJjJjttrpY0bKTx9CLs5U1q8Lctt3mzidYkR0YU/xNPYhuNKfe/NQpoWhnq/FRoGOy739J9X8CpReHbS5LT1aB7amQGCavzLqXh3o1A5yDaoaQ5yStf2BWEYyoUJC6n3GJjyLdEiMYBVu3dWVIkWuLOsJMbETuA0rRYxIavI1BoawzSxpb8nOTEuk4ETBNCE/QHKz9PeQrCHEKAkd+tWz4zzA42XIPlhcKPafP59/XVDDwGxXbgutTMB0tYWb0autVvFsoYDQ+pNxQlOEaPed/6LM9nAzJ8znG31NqFI=

notifications:
  email: false
