language: node_js

node_js:
  - node

before_script:
  - npm install -g jasmine
  - npm install

script:
  - npm test

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info

addons:
  code_climate:
  repo_token:
    secure:

notifications:
  email: false
